#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class Image;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace Universal
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::VisualState^ wideState;
        private: ::Windows::UI::Xaml::VisualState^ narrowState;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ MainStack;
        private: ::Windows::UI::Xaml::Controls::Image^ Image;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ Controls;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ Labels;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ Buttons;
        private: ::Windows::UI::Xaml::Controls::Button^ BtnPick;
        private: ::Windows::UI::Xaml::Controls::Button^ BtnReset;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock6;
    };
}

